#!/usr/bin/env bash 
#clean up exisiting dir
rm -rf $HOME/.dotfiles/
echo "removed dotfiles folder"
git clone --bare https://github.com/TeelyTao/dotfiles.git $HOME/.dotfiles
# define config alias locally since the dotfiles aren't installed on the system yet
function config {
   git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@
}
# create a directory to backup existing dotfiles to
mkdir -p .dotfiles-backup
config checkout
if [ $? = 0 ]; then
  echo "Checked out dotfiles from git@github.com:TeelyTao/dotfiles.git";
  else
    echo "Moving existing dotfiles to ~/.dotfiles-backup";
    config checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .dotfiles-backup/{}
    #Remove config-init and README.md
    rm config-init README.md
fi
# checkout dotfiles from repo
config checkout
config config status.showUntrackedFiles no
#clean up cloned repo
